### ISSUE TITLE
ContextGDIPlus.h does not build

### ISSUE THREAD

**Issue by avaer** [Sometrik/canvas#88]
There are typos in the file (double comma), among other things, that makes it not compile with VS.

https://github.com/Sometrik/canvas/blob/master/include/ContextGDIPlus.h#L69

**Comment by rekola** [comment]
Thank you. The GDI+ version of the canvas is currently unmaintained, but I will see what I can do about these problems.

**Comment by BrandonDyer64** [comment]
Any word on this issue? If not, is there an alternative library to canvas?

**Comment by rekola** [comment]
Fixed in several commits. GDIPlus version is now maintained.
